### ISSUE TITLE
运行run_prompt.py报错

### ISSUE THREAD

**Issue by tunuh-web** [HITSZ-HLT/ToSarcasm#2]
![image](https://github.com/HITSZ-HLT/ToSarcasm/assets/77224259/54c8cff4-2b18-49f2-ae2b-821805ee323f)

可以请问遇到这种情况改如何去解决吗

**Comment by lzjjeff** [comment]
> 

这个问题应该是由于运行run_prompt.py时缺少--do_eval参数导致无返回值造成的，我在代码中修复了这个bug，可以重新pull一下
